language: python

python:
  - "2.7"
  - "3.6"  

install: 
  - pip install tox-travis
  - pip install codecov
  
script: 
  - tox -- "\"--cov=critics\""

after_success:
  - codecov

deploy:
  provider: script
  script: make travis-build-docker
  on:
    branch: master
